// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrLip3DqRBc0aB_4l8xSZHNFwbnbEQwE',
    appId: '1:651862220099:web:2578d6584bf05b983d23f6',
    messagingSenderId: '651862220099',
    projectId: 'db-bol',
    authDomain: 'db-bol.firebaseapp.com',
    storageBucket: 'db-bol.appspot.com',
    measurementId: 'G-S49XBVHVKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFgr-IqGi6bgnv2ev66HTfZgvfuxLUoA',
    appId: '1:651862220099:android:3f7b59f1ee7f54f93d23f6',
    messagingSenderId: '651862220099',
    projectId: 'db-bol',
    storageBucket: 'db-bol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Wc9drVJqcwGBw5qXJF4mLP_sB8sm5Qg',
    appId: '1:651862220099:ios:19e0ae16004bc0b83d23f6',
    messagingSenderId: '651862220099',
    projectId: 'db-bol',
    storageBucket: 'db-bol.appspot.com',
    iosBundleId: 'com.elroir.dbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Wc9drVJqcwGBw5qXJF4mLP_sB8sm5Qg',
    appId: '1:651862220099:ios:97d5bcf04be410a83d23f6',
    messagingSenderId: '651862220099',
    projectId: 'db-bol',
    storageBucket: 'db-bol.appspot.com',
    iosBundleId: 'com.elroir.bolSit.bolSit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPrLip3DqRBc0aB_4l8xSZHNFwbnbEQwE',
    appId: '1:651862220099:web:16e685cb96a6b5643d23f6',
    messagingSenderId: '651862220099',
    projectId: 'db-bol',
    authDomain: 'db-bol.firebaseapp.com',
    storageBucket: 'db-bol.appspot.com',
    measurementId: 'G-Y4LJXYJTBJ',
  );
}
